### ISSUE TITLE
Add some shell protection?

### ISSUE THREAD

**Issue by neelsmith** [ryanfb/iiif-dl#1]
First manifest I tried was D'Orville 301 from Bodleian, and it looks like the montage command passed along a file name assembled from parts of the manifest that had both apostrophes and parentheses, to the unhappiness of the shell process.  Protect some of these or otherwise generate shell-safe filenames?

**Comment by ryanfb** [comment]
As of https://github.com/ryanfb/iiif-dl/commit/66c2c10a9c63f952c00324baf02d08a28e242fc6, the only allowed characters in the output filename should be `-.a-zA-Z0-9_`, does that fix the issue for you?

**Comment by neelsmith** [comment]
Works for every shell I use!
