### ISSUE TITLE
Latest docker image not synced with current code?

### ISSUE THREAD

**Issue by neelsmith** [ryanfb/iiif-dl#10]
I expected these two commands to produced identical results:

```
docker run -t -v $(pwd):/data ryanfb/iiif-dl  MANIFEST-FILE
bundle exec ./iiif-dl.rb  MANIFEST-FILE
```

but the dockerized example threw  errors about deprecated or out-of-date requests when I tried with a locally downloaded copy of this IIIF manifest: <https://iiif.bodleian.ox.ac.uk/iiif/manifestloader?manifest=//iiif.bodleian.ox.ac.uk/iiif/manifest/79e4df12-51e6-42a2-aaf6-ff5ff3cfb50d.json&canvas=//iiif.bodleian.ox.ac.uk/iiif/canvas/79e4df12-51e6-42a2-aaf6-ff5ff3cfb50d.json>

No such objections when running the ruby script locally with `bundle exec` (using ruby 2.5.1)

**Comment by ryanfb** [comment]
Just tested and I see the same thing. Thanks for bringing this to my attention, will investigate and attempt a fix.

**Comment by ryanfb** [comment]
Looks like the issue was the Docker build using `ruby:latest`, which is now 2.7.1, which obsoletes several URI methods which were in use. Once the pushed fix builds on Docker Hub, the latest Docker image should work again. The fix should be back-compatible with at least 2.5.x.
